title:               Celeste
url:                 https://nicoelayda.github.io
baseurl:             "/blog"

markdown:            kramdown
kramdown:
  math_engine: mathjax
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

blog:
  truncated_preview: false

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              Nico Elayda
  url:               nicoelayda.github.io
  email:             nico@elayda.com

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist

collections:
  projects:
    output: true
    permalink: /projects/:title/